// <auto-generated />
using System;
using Assignment4.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment4.Migrations.MyInitialMigration
{
    [DbContext(typeof(MMABooksContext))]
    partial class MMABooksContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assignment4.Models.Entities.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("CurrentBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AccountId")
                        .HasName("PK__Account__349DA5A627F95F7D");

                    b.ToTable("Account", (string)null);

                    b.HasData(
                        new
                        {
                            AccountId = 1,
                            AccountType = "Checking",
                            CurrentBalance = 1000.0,
                            DateCreated = new DateTime(2024, 4, 5, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3484),
                            UserId = 1
                        },
                        new
                        {
                            AccountId = 2,
                            AccountType = "Savings",
                            CurrentBalance = 2000.0,
                            DateCreated = new DateTime(2024, 4, 5, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3520),
                            UserId = 2
                        },
                        new
                        {
                            AccountId = 3,
                            AccountType = "Checking",
                            CurrentBalance = 3000.0,
                            DateCreated = new DateTime(2024, 4, 5, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3541),
                            UserId = 3
                        },
                        new
                        {
                            AccountId = 4,
                            AccountType = "Savings",
                            CurrentBalance = 4000.0,
                            DateCreated = new DateTime(2024, 4, 5, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3583),
                            UserId = 4
                        },
                        new
                        {
                            AccountId = 5,
                            AccountType = "Checking",
                            CurrentBalance = 5000.0,
                            DateCreated = new DateTime(2024, 4, 5, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3604),
                            UserId = 5
                        },
                        new
                        {
                            AccountId = 6,
                            AccountType = "Savings",
                            CurrentBalance = 6000.0,
                            DateCreated = new DateTime(2024, 4, 5, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3624),
                            UserId = 6
                        },
                        new
                        {
                            AccountId = 7,
                            AccountType = "Checking",
                            CurrentBalance = 7000.0,
                            DateCreated = new DateTime(2024, 4, 5, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3644),
                            UserId = 7
                        },
                        new
                        {
                            AccountId = 8,
                            AccountType = "Savings",
                            CurrentBalance = 8000.0,
                            DateCreated = new DateTime(2024, 4, 5, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3687),
                            UserId = 8
                        },
                        new
                        {
                            AccountId = 9,
                            AccountType = "Checking",
                            CurrentBalance = 9000.0,
                            DateCreated = new DateTime(2024, 4, 5, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3707),
                            UserId = 9
                        },
                        new
                        {
                            AccountId = 10,
                            AccountType = "Savings",
                            CurrentBalance = 10000.0,
                            DateCreated = new DateTime(2024, 4, 5, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3739),
                            UserId = 10
                        });
                });

            modelBuilder.Entity("Assignment4.Models.Entities.TransactionHistory", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("TransactionId")
                        .HasName("PK__Transact__55433A6B7EE3B2CD");

                    b.ToTable("TransactionHistory", (string)null);

                    b.HasData(
                        new
                        {
                            TransactionId = 11,
                            AccountId = 1,
                            Amount = 100m,
                            Description = "Transaction 1 for Account 1",
                            TransactionDate = new DateTime(2024, 4, 4, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3490)
                        },
                        new
                        {
                            TransactionId = 12,
                            AccountId = 1,
                            Amount = 200m,
                            Description = "Transaction 2 for Account 1",
                            TransactionDate = new DateTime(2024, 4, 3, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3501)
                        },
                        new
                        {
                            TransactionId = 13,
                            AccountId = 1,
                            Amount = 300m,
                            Description = "Transaction 3 for Account 1",
                            TransactionDate = new DateTime(2024, 4, 2, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3503)
                        },
                        new
                        {
                            TransactionId = 14,
                            AccountId = 1,
                            Amount = 400m,
                            Description = "Transaction 4 for Account 1",
                            TransactionDate = new DateTime(2024, 4, 1, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3505)
                        },
                        new
                        {
                            TransactionId = 15,
                            AccountId = 1,
                            Amount = 500m,
                            Description = "Transaction 5 for Account 1",
                            TransactionDate = new DateTime(2024, 3, 31, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3507)
                        },
                        new
                        {
                            TransactionId = 16,
                            AccountId = 1,
                            Amount = 600m,
                            Description = "Transaction 6 for Account 1",
                            TransactionDate = new DateTime(2024, 3, 30, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3510)
                        },
                        new
                        {
                            TransactionId = 17,
                            AccountId = 1,
                            Amount = 700m,
                            Description = "Transaction 7 for Account 1",
                            TransactionDate = new DateTime(2024, 3, 29, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3512)
                        },
                        new
                        {
                            TransactionId = 18,
                            AccountId = 1,
                            Amount = 800m,
                            Description = "Transaction 8 for Account 1",
                            TransactionDate = new DateTime(2024, 3, 28, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3514)
                        },
                        new
                        {
                            TransactionId = 19,
                            AccountId = 1,
                            Amount = 900m,
                            Description = "Transaction 9 for Account 1",
                            TransactionDate = new DateTime(2024, 3, 27, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3515)
                        },
                        new
                        {
                            TransactionId = 20,
                            AccountId = 1,
                            Amount = 1000m,
                            Description = "Transaction 10 for Account 1",
                            TransactionDate = new DateTime(2024, 3, 26, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3518)
                        },
                        new
                        {
                            TransactionId = 21,
                            AccountId = 2,
                            Amount = 100m,
                            Description = "Transaction 1 for Account 2",
                            TransactionDate = new DateTime(2024, 4, 4, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3522)
                        },
                        new
                        {
                            TransactionId = 22,
                            AccountId = 2,
                            Amount = 200m,
                            Description = "Transaction 2 for Account 2",
                            TransactionDate = new DateTime(2024, 4, 3, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3524)
                        },
                        new
                        {
                            TransactionId = 23,
                            AccountId = 2,
                            Amount = 300m,
                            Description = "Transaction 3 for Account 2",
                            TransactionDate = new DateTime(2024, 4, 2, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3526)
                        },
                        new
                        {
                            TransactionId = 24,
                            AccountId = 2,
                            Amount = 400m,
                            Description = "Transaction 4 for Account 2",
                            TransactionDate = new DateTime(2024, 4, 1, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3527)
                        },
                        new
                        {
                            TransactionId = 25,
                            AccountId = 2,
                            Amount = 500m,
                            Description = "Transaction 5 for Account 2",
                            TransactionDate = new DateTime(2024, 3, 31, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3530)
                        },
                        new
                        {
                            TransactionId = 26,
                            AccountId = 2,
                            Amount = 600m,
                            Description = "Transaction 6 for Account 2",
                            TransactionDate = new DateTime(2024, 3, 30, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3531)
                        },
                        new
                        {
                            TransactionId = 27,
                            AccountId = 2,
                            Amount = 700m,
                            Description = "Transaction 7 for Account 2",
                            TransactionDate = new DateTime(2024, 3, 29, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3533)
                        },
                        new
                        {
                            TransactionId = 28,
                            AccountId = 2,
                            Amount = 800m,
                            Description = "Transaction 8 for Account 2",
                            TransactionDate = new DateTime(2024, 3, 28, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3536)
                        },
                        new
                        {
                            TransactionId = 29,
                            AccountId = 2,
                            Amount = 900m,
                            Description = "Transaction 9 for Account 2",
                            TransactionDate = new DateTime(2024, 3, 27, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3538)
                        },
                        new
                        {
                            TransactionId = 30,
                            AccountId = 2,
                            Amount = 1000m,
                            Description = "Transaction 10 for Account 2",
                            TransactionDate = new DateTime(2024, 3, 26, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3539)
                        },
                        new
                        {
                            TransactionId = 31,
                            AccountId = 3,
                            Amount = 100m,
                            Description = "Transaction 1 for Account 3",
                            TransactionDate = new DateTime(2024, 4, 4, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3542)
                        },
                        new
                        {
                            TransactionId = 32,
                            AccountId = 3,
                            Amount = 200m,
                            Description = "Transaction 2 for Account 3",
                            TransactionDate = new DateTime(2024, 4, 3, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3544)
                        },
                        new
                        {
                            TransactionId = 33,
                            AccountId = 3,
                            Amount = 300m,
                            Description = "Transaction 3 for Account 3",
                            TransactionDate = new DateTime(2024, 4, 2, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3546)
                        },
                        new
                        {
                            TransactionId = 34,
                            AccountId = 3,
                            Amount = 400m,
                            Description = "Transaction 4 for Account 3",
                            TransactionDate = new DateTime(2024, 4, 1, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3548)
                        },
                        new
                        {
                            TransactionId = 35,
                            AccountId = 3,
                            Amount = 500m,
                            Description = "Transaction 5 for Account 3",
                            TransactionDate = new DateTime(2024, 3, 31, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3550)
                        },
                        new
                        {
                            TransactionId = 36,
                            AccountId = 3,
                            Amount = 600m,
                            Description = "Transaction 6 for Account 3",
                            TransactionDate = new DateTime(2024, 3, 30, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3552)
                        },
                        new
                        {
                            TransactionId = 37,
                            AccountId = 3,
                            Amount = 700m,
                            Description = "Transaction 7 for Account 3",
                            TransactionDate = new DateTime(2024, 3, 29, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3554)
                        },
                        new
                        {
                            TransactionId = 38,
                            AccountId = 3,
                            Amount = 800m,
                            Description = "Transaction 8 for Account 3",
                            TransactionDate = new DateTime(2024, 3, 28, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3556)
                        },
                        new
                        {
                            TransactionId = 39,
                            AccountId = 3,
                            Amount = 900m,
                            Description = "Transaction 9 for Account 3",
                            TransactionDate = new DateTime(2024, 3, 27, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3579)
                        },
                        new
                        {
                            TransactionId = 40,
                            AccountId = 3,
                            Amount = 1000m,
                            Description = "Transaction 10 for Account 3",
                            TransactionDate = new DateTime(2024, 3, 26, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3581)
                        },
                        new
                        {
                            TransactionId = 41,
                            AccountId = 4,
                            Amount = 100m,
                            Description = "Transaction 1 for Account 4",
                            TransactionDate = new DateTime(2024, 4, 4, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3584)
                        },
                        new
                        {
                            TransactionId = 42,
                            AccountId = 4,
                            Amount = 200m,
                            Description = "Transaction 2 for Account 4",
                            TransactionDate = new DateTime(2024, 4, 3, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3586)
                        },
                        new
                        {
                            TransactionId = 43,
                            AccountId = 4,
                            Amount = 300m,
                            Description = "Transaction 3 for Account 4",
                            TransactionDate = new DateTime(2024, 4, 2, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3588)
                        },
                        new
                        {
                            TransactionId = 44,
                            AccountId = 4,
                            Amount = 400m,
                            Description = "Transaction 4 for Account 4",
                            TransactionDate = new DateTime(2024, 4, 1, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3591)
                        },
                        new
                        {
                            TransactionId = 45,
                            AccountId = 4,
                            Amount = 500m,
                            Description = "Transaction 5 for Account 4",
                            TransactionDate = new DateTime(2024, 3, 31, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3592)
                        },
                        new
                        {
                            TransactionId = 46,
                            AccountId = 4,
                            Amount = 600m,
                            Description = "Transaction 6 for Account 4",
                            TransactionDate = new DateTime(2024, 3, 30, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3594)
                        },
                        new
                        {
                            TransactionId = 47,
                            AccountId = 4,
                            Amount = 700m,
                            Description = "Transaction 7 for Account 4",
                            TransactionDate = new DateTime(2024, 3, 29, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3596)
                        },
                        new
                        {
                            TransactionId = 48,
                            AccountId = 4,
                            Amount = 800m,
                            Description = "Transaction 8 for Account 4",
                            TransactionDate = new DateTime(2024, 3, 28, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3598)
                        },
                        new
                        {
                            TransactionId = 49,
                            AccountId = 4,
                            Amount = 900m,
                            Description = "Transaction 9 for Account 4",
                            TransactionDate = new DateTime(2024, 3, 27, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3600)
                        },
                        new
                        {
                            TransactionId = 50,
                            AccountId = 4,
                            Amount = 1000m,
                            Description = "Transaction 10 for Account 4",
                            TransactionDate = new DateTime(2024, 3, 26, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3601)
                        },
                        new
                        {
                            TransactionId = 51,
                            AccountId = 5,
                            Amount = 100m,
                            Description = "Transaction 1 for Account 5",
                            TransactionDate = new DateTime(2024, 4, 4, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3605)
                        },
                        new
                        {
                            TransactionId = 52,
                            AccountId = 5,
                            Amount = 200m,
                            Description = "Transaction 2 for Account 5",
                            TransactionDate = new DateTime(2024, 4, 3, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3607)
                        },
                        new
                        {
                            TransactionId = 53,
                            AccountId = 5,
                            Amount = 300m,
                            Description = "Transaction 3 for Account 5",
                            TransactionDate = new DateTime(2024, 4, 2, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3609)
                        },
                        new
                        {
                            TransactionId = 54,
                            AccountId = 5,
                            Amount = 400m,
                            Description = "Transaction 4 for Account 5",
                            TransactionDate = new DateTime(2024, 4, 1, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3611)
                        },
                        new
                        {
                            TransactionId = 55,
                            AccountId = 5,
                            Amount = 500m,
                            Description = "Transaction 5 for Account 5",
                            TransactionDate = new DateTime(2024, 3, 31, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3613)
                        },
                        new
                        {
                            TransactionId = 56,
                            AccountId = 5,
                            Amount = 600m,
                            Description = "Transaction 6 for Account 5",
                            TransactionDate = new DateTime(2024, 3, 30, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3615)
                        },
                        new
                        {
                            TransactionId = 57,
                            AccountId = 5,
                            Amount = 700m,
                            Description = "Transaction 7 for Account 5",
                            TransactionDate = new DateTime(2024, 3, 29, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3616)
                        },
                        new
                        {
                            TransactionId = 58,
                            AccountId = 5,
                            Amount = 800m,
                            Description = "Transaction 8 for Account 5",
                            TransactionDate = new DateTime(2024, 3, 28, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3618)
                        },
                        new
                        {
                            TransactionId = 59,
                            AccountId = 5,
                            Amount = 900m,
                            Description = "Transaction 9 for Account 5",
                            TransactionDate = new DateTime(2024, 3, 27, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3620)
                        },
                        new
                        {
                            TransactionId = 60,
                            AccountId = 5,
                            Amount = 1000m,
                            Description = "Transaction 10 for Account 5",
                            TransactionDate = new DateTime(2024, 3, 26, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3622)
                        },
                        new
                        {
                            TransactionId = 61,
                            AccountId = 6,
                            Amount = 100m,
                            Description = "Transaction 1 for Account 6",
                            TransactionDate = new DateTime(2024, 4, 4, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3625)
                        },
                        new
                        {
                            TransactionId = 62,
                            AccountId = 6,
                            Amount = 200m,
                            Description = "Transaction 2 for Account 6",
                            TransactionDate = new DateTime(2024, 4, 3, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3627)
                        },
                        new
                        {
                            TransactionId = 63,
                            AccountId = 6,
                            Amount = 300m,
                            Description = "Transaction 3 for Account 6",
                            TransactionDate = new DateTime(2024, 4, 2, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3629)
                        },
                        new
                        {
                            TransactionId = 64,
                            AccountId = 6,
                            Amount = 400m,
                            Description = "Transaction 4 for Account 6",
                            TransactionDate = new DateTime(2024, 4, 1, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3631)
                        },
                        new
                        {
                            TransactionId = 65,
                            AccountId = 6,
                            Amount = 500m,
                            Description = "Transaction 5 for Account 6",
                            TransactionDate = new DateTime(2024, 3, 31, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3632)
                        },
                        new
                        {
                            TransactionId = 66,
                            AccountId = 6,
                            Amount = 600m,
                            Description = "Transaction 6 for Account 6",
                            TransactionDate = new DateTime(2024, 3, 30, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3634)
                        },
                        new
                        {
                            TransactionId = 67,
                            AccountId = 6,
                            Amount = 700m,
                            Description = "Transaction 7 for Account 6",
                            TransactionDate = new DateTime(2024, 3, 29, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3636)
                        },
                        new
                        {
                            TransactionId = 68,
                            AccountId = 6,
                            Amount = 800m,
                            Description = "Transaction 8 for Account 6",
                            TransactionDate = new DateTime(2024, 3, 28, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3638)
                        },
                        new
                        {
                            TransactionId = 69,
                            AccountId = 6,
                            Amount = 900m,
                            Description = "Transaction 9 for Account 6",
                            TransactionDate = new DateTime(2024, 3, 27, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3640)
                        },
                        new
                        {
                            TransactionId = 70,
                            AccountId = 6,
                            Amount = 1000m,
                            Description = "Transaction 10 for Account 6",
                            TransactionDate = new DateTime(2024, 3, 26, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3642)
                        },
                        new
                        {
                            TransactionId = 71,
                            AccountId = 7,
                            Amount = 100m,
                            Description = "Transaction 1 for Account 7",
                            TransactionDate = new DateTime(2024, 4, 4, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3645)
                        },
                        new
                        {
                            TransactionId = 72,
                            AccountId = 7,
                            Amount = 200m,
                            Description = "Transaction 2 for Account 7",
                            TransactionDate = new DateTime(2024, 4, 3, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3647)
                        },
                        new
                        {
                            TransactionId = 73,
                            AccountId = 7,
                            Amount = 300m,
                            Description = "Transaction 3 for Account 7",
                            TransactionDate = new DateTime(2024, 4, 2, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3648)
                        },
                        new
                        {
                            TransactionId = 74,
                            AccountId = 7,
                            Amount = 400m,
                            Description = "Transaction 4 for Account 7",
                            TransactionDate = new DateTime(2024, 4, 1, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3650)
                        },
                        new
                        {
                            TransactionId = 75,
                            AccountId = 7,
                            Amount = 500m,
                            Description = "Transaction 5 for Account 7",
                            TransactionDate = new DateTime(2024, 3, 31, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3652)
                        },
                        new
                        {
                            TransactionId = 76,
                            AccountId = 7,
                            Amount = 600m,
                            Description = "Transaction 6 for Account 7",
                            TransactionDate = new DateTime(2024, 3, 30, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3654)
                        },
                        new
                        {
                            TransactionId = 77,
                            AccountId = 7,
                            Amount = 700m,
                            Description = "Transaction 7 for Account 7",
                            TransactionDate = new DateTime(2024, 3, 29, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3656)
                        },
                        new
                        {
                            TransactionId = 78,
                            AccountId = 7,
                            Amount = 800m,
                            Description = "Transaction 8 for Account 7",
                            TransactionDate = new DateTime(2024, 3, 28, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3658)
                        },
                        new
                        {
                            TransactionId = 79,
                            AccountId = 7,
                            Amount = 900m,
                            Description = "Transaction 9 for Account 7",
                            TransactionDate = new DateTime(2024, 3, 27, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3660)
                        },
                        new
                        {
                            TransactionId = 80,
                            AccountId = 7,
                            Amount = 1000m,
                            Description = "Transaction 10 for Account 7",
                            TransactionDate = new DateTime(2024, 3, 26, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3685)
                        },
                        new
                        {
                            TransactionId = 81,
                            AccountId = 8,
                            Amount = 100m,
                            Description = "Transaction 1 for Account 8",
                            TransactionDate = new DateTime(2024, 4, 4, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3688)
                        },
                        new
                        {
                            TransactionId = 82,
                            AccountId = 8,
                            Amount = 200m,
                            Description = "Transaction 2 for Account 8",
                            TransactionDate = new DateTime(2024, 4, 3, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3690)
                        },
                        new
                        {
                            TransactionId = 83,
                            AccountId = 8,
                            Amount = 300m,
                            Description = "Transaction 3 for Account 8",
                            TransactionDate = new DateTime(2024, 4, 2, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3692)
                        },
                        new
                        {
                            TransactionId = 84,
                            AccountId = 8,
                            Amount = 400m,
                            Description = "Transaction 4 for Account 8",
                            TransactionDate = new DateTime(2024, 4, 1, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3694)
                        },
                        new
                        {
                            TransactionId = 85,
                            AccountId = 8,
                            Amount = 500m,
                            Description = "Transaction 5 for Account 8",
                            TransactionDate = new DateTime(2024, 3, 31, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3696)
                        },
                        new
                        {
                            TransactionId = 86,
                            AccountId = 8,
                            Amount = 600m,
                            Description = "Transaction 6 for Account 8",
                            TransactionDate = new DateTime(2024, 3, 30, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3698)
                        },
                        new
                        {
                            TransactionId = 87,
                            AccountId = 8,
                            Amount = 700m,
                            Description = "Transaction 7 for Account 8",
                            TransactionDate = new DateTime(2024, 3, 29, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3699)
                        },
                        new
                        {
                            TransactionId = 88,
                            AccountId = 8,
                            Amount = 800m,
                            Description = "Transaction 8 for Account 8",
                            TransactionDate = new DateTime(2024, 3, 28, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3701)
                        },
                        new
                        {
                            TransactionId = 89,
                            AccountId = 8,
                            Amount = 900m,
                            Description = "Transaction 9 for Account 8",
                            TransactionDate = new DateTime(2024, 3, 27, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3703)
                        },
                        new
                        {
                            TransactionId = 90,
                            AccountId = 8,
                            Amount = 1000m,
                            Description = "Transaction 10 for Account 8",
                            TransactionDate = new DateTime(2024, 3, 26, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3705)
                        },
                        new
                        {
                            TransactionId = 91,
                            AccountId = 9,
                            Amount = 100m,
                            Description = "Transaction 1 for Account 9",
                            TransactionDate = new DateTime(2024, 4, 4, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3709)
                        },
                        new
                        {
                            TransactionId = 92,
                            AccountId = 9,
                            Amount = 200m,
                            Description = "Transaction 2 for Account 9",
                            TransactionDate = new DateTime(2024, 4, 3, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3711)
                        },
                        new
                        {
                            TransactionId = 93,
                            AccountId = 9,
                            Amount = 300m,
                            Description = "Transaction 3 for Account 9",
                            TransactionDate = new DateTime(2024, 4, 2, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3712)
                        },
                        new
                        {
                            TransactionId = 94,
                            AccountId = 9,
                            Amount = 400m,
                            Description = "Transaction 4 for Account 9",
                            TransactionDate = new DateTime(2024, 4, 1, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3714)
                        },
                        new
                        {
                            TransactionId = 95,
                            AccountId = 9,
                            Amount = 500m,
                            Description = "Transaction 5 for Account 9",
                            TransactionDate = new DateTime(2024, 3, 31, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3717)
                        },
                        new
                        {
                            TransactionId = 96,
                            AccountId = 9,
                            Amount = 600m,
                            Description = "Transaction 6 for Account 9",
                            TransactionDate = new DateTime(2024, 3, 30, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3719)
                        },
                        new
                        {
                            TransactionId = 97,
                            AccountId = 9,
                            Amount = 700m,
                            Description = "Transaction 7 for Account 9",
                            TransactionDate = new DateTime(2024, 3, 29, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3731)
                        },
                        new
                        {
                            TransactionId = 98,
                            AccountId = 9,
                            Amount = 800m,
                            Description = "Transaction 8 for Account 9",
                            TransactionDate = new DateTime(2024, 3, 28, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3733)
                        },
                        new
                        {
                            TransactionId = 99,
                            AccountId = 9,
                            Amount = 900m,
                            Description = "Transaction 9 for Account 9",
                            TransactionDate = new DateTime(2024, 3, 27, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3735)
                        },
                        new
                        {
                            TransactionId = 100,
                            AccountId = 9,
                            Amount = 1000m,
                            Description = "Transaction 10 for Account 9",
                            TransactionDate = new DateTime(2024, 3, 26, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3737)
                        },
                        new
                        {
                            TransactionId = 101,
                            AccountId = 10,
                            Amount = 100m,
                            Description = "Transaction 1 for Account 10",
                            TransactionDate = new DateTime(2024, 4, 4, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3740)
                        },
                        new
                        {
                            TransactionId = 102,
                            AccountId = 10,
                            Amount = 200m,
                            Description = "Transaction 2 for Account 10",
                            TransactionDate = new DateTime(2024, 4, 3, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3742)
                        },
                        new
                        {
                            TransactionId = 103,
                            AccountId = 10,
                            Amount = 300m,
                            Description = "Transaction 3 for Account 10",
                            TransactionDate = new DateTime(2024, 4, 2, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3744)
                        },
                        new
                        {
                            TransactionId = 104,
                            AccountId = 10,
                            Amount = 400m,
                            Description = "Transaction 4 for Account 10",
                            TransactionDate = new DateTime(2024, 4, 1, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3746)
                        },
                        new
                        {
                            TransactionId = 105,
                            AccountId = 10,
                            Amount = 500m,
                            Description = "Transaction 5 for Account 10",
                            TransactionDate = new DateTime(2024, 3, 31, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3748)
                        },
                        new
                        {
                            TransactionId = 106,
                            AccountId = 10,
                            Amount = 600m,
                            Description = "Transaction 6 for Account 10",
                            TransactionDate = new DateTime(2024, 3, 30, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3750)
                        },
                        new
                        {
                            TransactionId = 107,
                            AccountId = 10,
                            Amount = 700m,
                            Description = "Transaction 7 for Account 10",
                            TransactionDate = new DateTime(2024, 3, 29, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3752)
                        },
                        new
                        {
                            TransactionId = 108,
                            AccountId = 10,
                            Amount = 800m,
                            Description = "Transaction 8 for Account 10",
                            TransactionDate = new DateTime(2024, 3, 28, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3753)
                        },
                        new
                        {
                            TransactionId = 109,
                            AccountId = 10,
                            Amount = 900m,
                            Description = "Transaction 9 for Account 10",
                            TransactionDate = new DateTime(2024, 3, 27, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3755)
                        },
                        new
                        {
                            TransactionId = 110,
                            AccountId = 10,
                            Amount = 1000m,
                            Description = "Transaction 10 for Account 10",
                            TransactionDate = new DateTime(2024, 3, 26, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3757)
                        });
                });

            modelBuilder.Entity("Assignment4.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__tmp_ms_x__3214EC07097F1A41");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2024, 4, 5, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3318),
                            Email = "user1@example.com",
                            Firstname = "Firstname1",
                            Lastname = "Lastname1",
                            Password = "hashed-password-1"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2024, 4, 5, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3385),
                            Email = "user2@example.com",
                            Firstname = "Firstname2",
                            Lastname = "Lastname2",
                            Password = "hashed-password-2"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2024, 4, 5, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3388),
                            Email = "user3@example.com",
                            Firstname = "Firstname3",
                            Lastname = "Lastname3",
                            Password = "hashed-password-3"
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2024, 4, 5, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3391),
                            Email = "user4@example.com",
                            Firstname = "Firstname4",
                            Lastname = "Lastname4",
                            Password = "hashed-password-4"
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2024, 4, 5, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3394),
                            Email = "user5@example.com",
                            Firstname = "Firstname5",
                            Lastname = "Lastname5",
                            Password = "hashed-password-5"
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(2024, 4, 5, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3399),
                            Email = "user6@example.com",
                            Firstname = "Firstname6",
                            Lastname = "Lastname6",
                            Password = "hashed-password-6"
                        },
                        new
                        {
                            Id = 7,
                            DateCreated = new DateTime(2024, 4, 5, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3402),
                            Email = "user7@example.com",
                            Firstname = "Firstname7",
                            Lastname = "Lastname7",
                            Password = "hashed-password-7"
                        },
                        new
                        {
                            Id = 8,
                            DateCreated = new DateTime(2024, 4, 5, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3405),
                            Email = "user8@example.com",
                            Firstname = "Firstname8",
                            Lastname = "Lastname8",
                            Password = "hashed-password-8"
                        },
                        new
                        {
                            Id = 9,
                            DateCreated = new DateTime(2024, 4, 5, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3408),
                            Email = "user9@example.com",
                            Firstname = "Firstname9",
                            Lastname = "Lastname9",
                            Password = "hashed-password-9"
                        },
                        new
                        {
                            Id = 10,
                            DateCreated = new DateTime(2024, 4, 5, 16, 35, 9, 267, DateTimeKind.Local).AddTicks(3413),
                            Email = "user10@example.com",
                            Firstname = "Firstname10",
                            Lastname = "Lastname10",
                            Password = "hashed-password-10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
